### ISSUE TITLE
[FEA] Tag for excluding variables from documentation

### ISSUE THREAD

**Issue by dbv-rl** [dbv-rl/ansible_doca#1]
Add support for a tag that leads to variables not being documented when marked.

```yaml
# Some description
#
# This variable will be ignored by doca
#
# doca: ignore
test_variable_1: foo

# Some description
# This variable will not be ignored by doca.
test_variable_2: foo
````
