### ISSUE TITLE
[FEA] Tag support for variables

### ISSUE THREAD

**Issue by dbv-rl** [dbv-rl/ansible_doca#2]
Add tag support for filtering

This would allow to create sections for eg. primary and secondary variables and fetch the documentation based on the the tag.
Other stuff like ignored-variables  could also be valid kind of tag?

Example:

```yaml
---
# Description
#
# doca: tag:1
variable_1: foobar

# Description
#
# doca: tag:1,2
variable_2: foobar
```

```bash
$ doca.py . --limit 1
variable_1
variable_2

$ doca.py . --limit 2
variable_"
```
