### ISSUE TITLE
[BUG] Variable not detected

### ISSUE THREAD

**Issue by dbv-rl** [dbv-rl/ansible_doca#4]
# Bug

When a variable has no assigned value in a variable file, doca does not include it into the output.

```yaml
---
testvar1: foobar

testvar2:
```

Output:

```yaml
testvar1: str
```
